import type { NextPage } from "next"
import Head from "next/head"
import React, { useEffect } from "react"
import { useEvent, useQueue } from "../hooks"
import type {
  TwitchChannelFollowEvent,
  TwitchChannelRedemptionEvent,
  TwitchChannelSubscribeEvent,
  TwitchEvent,
} from "../lib/twitch"
import { Notification } from "../components"
import { useRouter } from "next/router"
import { getReward } from "../lib/rewards"

const Home: NextPage = () => {
  const router = useRouter()
  const [, setNotifications, activeNotification] = useQueue<
    TwitchChannelFollowEvent | TwitchChannelSubscribeEvent
  >()
  const [, setSnapFilters, activeSnapFilter] =
    useQueue<TwitchChannelRedemptionEvent>(5 * 60 * 1000)
  const [, setRedemptions, activeRedemption] =
    useQueue<TwitchChannelRedemptionEvent>()

  const handleTwitchEvent = (event: TwitchEvent) => {
    if (event.type === "channel.follow" || event.type === "channel.subscribe") {
      setNotifications((notifications) => [...notifications, event])
    }
    if (event.type === "channel.channel_points_custom_reward_redemption.add") {
      const reward = getReward(event.event.reward.id)
      if (reward?.type === "snap-filter") {
        setSnapFilters((redemptions) => [...redemptions, event])
      } else {
        setRedemptions((redemptions) => [...redemptions, event])
      }
    }
  }

  useEvent<TwitchEvent>("twitch-event", (e) =>
    handleTwitchEvent({ ...e, type: e.subscription.type } as TwitchEvent)
  )

  useEffect(() => {
    const rewardId = activeRedemption?.event.reward.id
    const reward = getReward(rewardId)

    if (reward?.type === "shell") {
      fetch("/api/shell", {
        method: "post",
        body: JSON.stringify({ rewardId }),
      })
    }
  }, [activeRedemption])

  useEffect(() => {
    const rewardId = activeSnapFilter?.event.reward.id

    // If there's no active redemption, we need to toggle the snap filter off
    fetch("/api/snap", {
      method: "post",
      body: JSON.stringify({ rewardId }),
    })
  }, [activeSnapFilter])

  useEffect(() => {
    const timer = setInterval(() => {
      fetch(`/api/ping?id=${router.query.id}`, {
        method: "post",
      })
    }, 1000 * 5)
    return () => clearInterval(timer)
  }, [router.query.id])

  return (
    <div className="relative h-[1080px] w-[1920px]">
      <Head>
        <title>Adam&apos;s Twitch Overlay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {activeNotification && (
        <Notification>
          {contentFromTwitchEvent(activeNotification)}
        </Notification>
      )}
    </div>
  )
}

export default Home

function contentFromTwitchEvent(event: TwitchEvent) {
  switch (event.subscription.type) {
    case "channel.follow":
      return `${event.event.user_name} followed!`
    case "channel.subscribe":
      return `${event.event.user_name} subscribed!`

    default:
      break
  }
}
